site_name: Choon Yin's ____________
site_url: https://cyyeap.github.io/
theme:
  name: material
plugins:
  - blog: 
      archive_date_format: MMMM yyyy 
      post_date_format: full
      post_excerpt: optional
      post_readtime: true
  - search: 
      lang: 
        - en
        - de
        - zh